---
- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: started
    enabled: yes
  changed_when: false

# NOTE: This patch only effect Kraken. Fix when reboot machine, the monitor 
# service do not auto start. Fix proposed upstream: ceph/ceph#14226
- name: enable the ceph-mon.target service
  service:
    name: ceph-mon.target
    enabled: yes
  changed_when: false
